import type { Persona, Transaction, QuantoInsight, AdminControls, QuickAction } from "./types"

export const personas: Record<string, Persona> = {
  user_ada_f4k9: {
    id: "user_ada_f4k9",
    name: "Ada Okonkwo",
    personaType: "Salaried Employee",
    accountNumber: "1234567890",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ada",
    email: "ada.okonkwo@email.com",
    balance: 85430,
    usualMonthlySpend: 150000,
    currentSpend: 47000,
    savingsStreak: 0,
    salaryExpectedDate: "2025-11-01",
    lastSalaryDate: "2025-10-01",
    month: 11,
    transactions: [
      {
        id: "tx_1",
        date: "2025-11-12",
        vendor: "Starbucks Coffee",
        amount: 4500,
        category: "dining",
        type: "debit",
        icon: "☕",
      },
      {
        id: "tx_2",
        date: "2025-11-11",
        vendor: "Salary Deposit",
        amount: 285000,
        category: "income",
        type: "credit",
        icon: "💰",
      },
      {
        id: "tx_3",
        date: "2025-11-10",
        vendor: "Amazon Purchase",
        amount: 23500,
        category: "shopping",
        type: "debit",
        icon: "📦",
      },
      {
        id: "tx_4",
        date: "2025-11-09",
        vendor: "Electricity Bill",
        amount: 8200,
        category: "utilities",
        type: "debit",
        icon: "⚡",
      },
      {
        id: "tx_5",
        date: "2025-11-08",
        vendor: "Uber Trip",
        amount: 6800,
        category: "transport",
        type: "debit",
        icon: "🚗",
      },
      {
        id: "tx_6",
        date: "2025-11-07",
        vendor: "Netflix Subscription",
        amount: 2490,
        category: "entertainment",
        type: "debit",
        icon: "🎬",
      },
      {
        id: "tx_7",
        date: "2025-11-06",
        vendor: "Restaurant - The Bowl",
        amount: 18500,
        category: "dining",
        type: "debit",
        icon: "🍽️",
      },
      {
        id: "tx_8",
        date: "2025-11-05",
        vendor: "Gym Membership",
        amount: 15000,
        category: "health",
        type: "debit",
        icon: "💪",
      },
    ],
    quantoResponses: [
      {
        id: "flow_salary_delay",
        category: "empathetic",
        title: "Salary Delayed?",
        message: "We noticed your salary hasn't arrived yet. You'll enjoy free transactions for the next 24 hours.",
        actionLabel: "See eligible transactions",
        priority: "high",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        read: false,
        flowType: "salary_delay",
        flowData: { feeWaiverHours: 24, eligibleTransactionCount: 5 },
      },
    ],
  },
  user_malik_2p7j: {
    id: "user_malik_2p7j",
    name: "Malik Hassan",
    personaType: "Student",
    accountNumber: "1098765432",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Malik",
    email: "malik.hassan@email.com",
    balance: 32000,
    usualMonthlySpend: 50000,
    currentSpend: 57000,
    savingsStreak: 0,
    subscriptionData: [
      { name: "Netflix", amount: 2400, renewalDate: "2025-11-15", enabled: true },
      { name: "Apple Music", amount: 1800, renewalDate: "2025-11-15", enabled: true },
      { name: "Canva Pro", amount: 2900, renewalDate: "2025-11-14", enabled: true },
    ],
    month: 11,
    transactions: [
      {
        id: "tx_1",
        date: "2025-11-12",
        vendor: "Jumia Food",
        amount: 3200,
        category: "dining",
        type: "debit",
        icon: "🍕",
      },
      {
        id: "tx_2",
        date: "2025-11-11",
        vendor: "Data Plan",
        amount: 2500,
        category: "utilities",
        type: "debit",
        icon: "📡",
      },
      {
        id: "tx_3",
        date: "2025-11-10",
        vendor: "Games Purchase",
        amount: 8900,
        category: "entertainment",
        type: "debit",
        icon: "🎮",
      },
      {
        id: "tx_4",
        date: "2025-11-09",
        vendor: "Transfer from Mom",
        amount: 15000,
        category: "income",
        type: "credit",
        icon: "👨‍👩‍👦",
      },
      {
        id: "tx_5",
        date: "2025-11-08",
        vendor: "Coffee Shop",
        amount: 1500,
        category: "dining",
        type: "debit",
        icon: "☕",
      },
      {
        id: "tx_6",
        date: "2025-11-07",
        vendor: "Sportswear",
        amount: 12500,
        category: "shopping",
        type: "debit",
        icon: "👟",
      },
      {
        id: "tx_7",
        date: "2025-11-06",
        vendor: "Cinema Ticket",
        amount: 3500,
        category: "entertainment",
        type: "debit",
        icon: "🎬",
      },
      {
        id: "tx_8",
        date: "2025-11-05",
        vendor: "Airtime Topup",
        amount: 500,
        category: "utilities",
        type: "debit",
        icon: "📞",
      },
    ],
    quantoResponses: [
      {
        id: "flow_subscriptions",
        category: "preventive",
        title: "Subscription Renewals",
        message:
          "Heads up, 3 of your subscriptions renew this weekend. Total ₦7,100. Want to pause any for this month?",
        actionLabel: "Manage subscriptions",
        priority: "high",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        read: false,
        flowType: "subscription_warning",
        flowData: { renewalDate: "2025-11-15", subscriptions: 3, totalAmount: 7100 },
      },
    ],
  },
  user_ngozi_8m5n: {
    id: "user_ngozi_8m5n",
    name: "Ngozi Adeyemi",
    personaType: "New Mother",
    accountNumber: "5432109876",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ngozi",
    email: "ngozi.adeyemi@email.com",
    balance: 395000,
    usualMonthlySpend: 45000,
    currentSpend: 40000,
    savingsStreak: 1,
    month: 12,
    recentFlightPurchase: true,
    transactions: [
      {
        id: "tx_1",
        date: "2025-11-12",
        vendor: "Baby Store",
        amount: 12000,
        category: "shopping",
        type: "debit",
        icon: "👶",
      },
      {
        id: "tx_2",
        date: "2025-11-11",
        vendor: "Pharmacy",
        amount: 5600,
        category: "health",
        type: "debit",
        icon: "💊",
      },
      {
        id: "tx_3",
        date: "2025-11-10",
        vendor: "Grocery Store",
        amount: 8900,
        category: "shopping",
        type: "debit",
        icon: "🛒",
      },
      {
        id: "tx_4",
        date: "2025-11-09",
        vendor: "Salary Transfer",
        amount: 120000,
        category: "income",
        type: "credit",
        icon: "💰",
      },
      {
        id: "tx_5",
        date: "2025-11-08",
        vendor: "Utilities",
        amount: 3200,
        category: "utilities",
        type: "debit",
        icon: "⚡",
      },
      {
        id: "tx_6",
        date: "2025-11-07",
        vendor: "Nanny Payment",
        amount: 25000,
        category: "services",
        type: "debit",
        icon: "👨‍🍼",
      },
      {
        id: "tx_7",
        date: "2025-11-06",
        vendor: "Hospital Checkup",
        amount: 15000,
        category: "health",
        type: "debit",
        icon: "🏥",
      },
      {
        id: "tx_8",
        date: "2025-11-05",
        vendor: "Transport",
        amount: 2400,
        category: "transport",
        type: "debit",
        icon: "🚕",
      },
    ],
    quantoResponses: [
      {
        id: "flow_reward",
        category: "reward",
        title: "Exclusive Travel Offer",
        message: "Flying soon! You just unlocked 15% off your travel ticket for your next trip. Bon air ✈️",
        actionLabel: "View offer",
        priority: "medium",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        read: false,
        flowType: "reward_offer",
        flowData: {
          partner: "Air Peace",
          discount: "15%",
          promoCode: "AIRPEACE15",
          expiryDate: "2025-12-31",
        },
      },
    ],
  },
  user_tolu_6x2k: {
    id: "user_tolu_6x2k",
    name: "Tolu Okafor",
    personaType: "Freelancer",
    accountNumber: "9876543210",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tolu",
    email: "tolu.okafor@email.com",
    balance: 280000,
    usualMonthlySpend: 65000,
    currentSpend: 41000,
    savingsStreak: 0,
    spendingInThreeDays: 180000,
    lastSalaryDate: "2025-11-10",
    month: 11,
    transactions: [
      {
        id: "tx_1",
        date: "2025-11-12",
        vendor: "Coffee Meeting",
        amount: 2500,
        category: "dining",
        type: "debit",
        icon: "☕",
      },
      {
        id: "tx_2",
        date: "2025-11-11",
        vendor: "Client Payment",
        amount: 150000,
        category: "income",
        type: "credit",
        icon: "💼",
      },
      {
        id: "tx_3",
        date: "2025-11-10",
        vendor: "Software Subscription",
        amount: 8900,
        category: "utilities",
        type: "debit",
        icon: "💻",
      },
      {
        id: "tx_4",
        date: "2025-11-09",
        vendor: "Office Supplies",
        amount: 6200,
        category: "shopping",
        type: "debit",
        icon: "📝",
      },
      {
        id: "tx_5",
        date: "2025-11-08",
        vendor: "Co-working Space",
        amount: 12000,
        category: "services",
        type: "debit",
        icon: "🏢",
      },
      {
        id: "tx_6",
        date: "2025-11-07",
        vendor: "Client Payment",
        amount: 120000,
        category: "income",
        type: "credit",
        icon: "💼",
      },
      {
        id: "tx_7",
        date: "2025-11-06",
        vendor: "Internet Bill",
        amount: 5000,
        category: "utilities",
        type: "debit",
        icon: "📡",
      },
      {
        id: "tx_8",
        date: "2025-11-05",
        vendor: "Equipment Purchase",
        amount: 45000,
        category: "shopping",
        type: "debit",
        icon: "⚙️",
      },
    ],
    quantoResponses: [
      {
        id: "flow_cooloff",
        category: "educational",
        title: "Spending Alert",
        message:
          "You've spent 60% of your salary within 3 days. Setting a 24-hour 'cool-off' before big spends could help your budget go further. Want me to set it up?",
        actionLabel: "Activate cool-off",
        priority: "high",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        read: false,
        flowType: "spending_cooloff",
        flowData: { cooloffHours: 24, spendingPercentage: 60 },
      },
    ],
  },
  user_raymond_9q3r: {
    id: "user_raymond_9q3r",
    name: "Raymond Ejiofor",
    personaType: "Small Business Owner",
    accountNumber: "5678901234",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Raymond",
    email: "raymond.ejiofor@email.com",
    balance: 520000,
    usualMonthlySpend: 120000,
    currentSpend: 95000,
    savingsStreak: 3,
    month: 12,
    transactions: [
      {
        id: "tx_1",
        date: "2025-11-12",
        vendor: "Inventory Purchase",
        amount: 85000,
        category: "business",
        type: "debit",
        icon: "📦",
      },
      {
        id: "tx_2",
        date: "2025-11-11",
        vendor: "Sales Revenue",
        amount: 320000,
        category: "income",
        type: "credit",
        icon: "💰",
      },
      {
        id: "tx_3",
        date: "2025-11-10",
        vendor: "Staff Salaries",
        amount: 65000,
        category: "business",
        type: "debit",
        icon: "👨‍💼",
      },
      {
        id: "tx_4",
        date: "2025-11-09",
        vendor: "Business Rent",
        amount: 35000,
        category: "utilities",
        type: "debit",
        icon: "🏪",
      },
      {
        id: "tx_5",
        date: "2025-11-08",
        vendor: "Online Ads",
        amount: 12000,
        category: "business",
        type: "debit",
        icon: "📢",
      },
      {
        id: "tx_6",
        date: "2025-11-07",
        vendor: "Sales Revenue",
        amount: 280000,
        category: "income",
        type: "credit",
        icon: "💰",
      },
      {
        id: "tx_7",
        date: "2025-11-06",
        vendor: "Equipment Maintenance",
        amount: 8500,
        category: "business",
        type: "debit",
        icon: "🔧",
      },
      {
        id: "tx_8",
        date: "2025-11-05",
        vendor: "Supplier Payment",
        amount: 72000,
        category: "business",
        type: "debit",
        icon: "🚚",
      },
    ],
    quantoResponses: [
      {
        id: "flow_detty_december",
        category: "ambient",
        title: "Detty December Tracker",
        message:
          "It's Detty December 🎉 Before the duties take over, want a mini tracker to balance enjoyment and savings?",
        actionLabel: "Activate tracker",
        priority: "medium",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        read: false,
        flowType: "detty_december",
        flowData: { trackerTypes: ["Entertainment vs. Savings", "Food & Drinks"] },
      },
    ],
  },
}

export const quickActions: QuickAction[] = [
  { id: "pay_bills", label: "Pay Bills", icon: "📱", description: "Utilities, subscriptions" },
  { id: "buy_airtime", label: "Buy Airtime", icon: "📞", description: "Phone credit" },
  { id: "buy_data", label: "Buy Data", icon: "📡", description: "Internet plans" },
  { id: "service_subscriptions", label: "Subscriptions", icon: "🎬", description: "Streaming, apps" },
  { id: "transfer", label: "Transfer", icon: "➡️", description: "Send money" },
  { id: "investments", label: "Invest", icon: "📈", description: "Grow your money" },
]

export const mockUser = {
  id: "user_1",
  name: "Ada Okonkwo",
  email: "ada.okonkwo@email.com",
  phone: "+234 (0) 801 234 5678",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ada",
  accounts: [
    {
      id: "acc_1",
      name: "Checking Account",
      type: "checking",
      balance: 285430,
      accountNumber: "1234567890",
      routingNumber: "021000021",
    },
    {
      id: "acc_2",
      name: "Savings Account",
      type: "savings",
      balance: 450000,
      accountNumber: "0987654321",
      routingNumber: "021000021",
    },
  ],
  cards: [
    {
      id: "card_1",
      lastFour: "4242",
      type: "debit",
      cardholderName: "ADA OKONKWO",
      expiry: "12/26",
      isDefault: true,
      color: "from-blue-600 to-blue-800",
    },
    {
      id: "card_2",
      lastFour: "5555",
      type: "credit",
      cardholderName: "ADA OKONKWO",
      expiry: "08/25",
      isDefault: false,
      color: "from-purple-600 to-purple-800",
    },
  ],
}

export const recentTransactions: Transaction[] = [
  {
    id: "tx_1",
    date: "2025-11-12",
    vendor: "Starbucks Coffee",
    amount: 4500,
    category: "dining",
    type: "debit",
    icon: "☕",
  },
  {
    id: "tx_2",
    date: "2025-11-11",
    vendor: "Salary Deposit",
    amount: 285000,
    category: "income",
    type: "credit",
    icon: "💰",
  },
  {
    id: "tx_3",
    date: "2025-11-10",
    vendor: "Amazon Purchase",
    amount: 23500,
    category: "shopping",
    type: "debit",
    icon: "📦",
  },
  {
    id: "tx_4",
    date: "2025-11-09",
    vendor: "Electricity Bill",
    amount: 8200,
    category: "utilities",
    type: "debit",
    icon: "⚡",
  },
  {
    id: "tx_5",
    date: "2025-11-08",
    vendor: "Uber Trip",
    amount: 6800,
    category: "transport",
    type: "debit",
    icon: "🚗",
  },
  {
    id: "tx_6",
    date: "2025-11-07",
    vendor: "Netflix Subscription",
    amount: 2490,
    category: "entertainment",
    type: "debit",
    icon: "🎬",
  },
  {
    id: "tx_7",
    date: "2025-11-06",
    vendor: "Restaurant - The Bowl",
    amount: 18500,
    category: "dining",
    type: "debit",
    icon: "🍽️",
  },
  {
    id: "tx_8",
    date: "2025-11-05",
    vendor: "Gym Membership",
    amount: 15000,
    category: "health",
    type: "debit",
    icon: "💪",
  },
]

export const quantoInsights: QuantoInsight[] = [
  {
    id: "insight_1",
    category: "preventive",
    title: "Spending Alert",
    message: "You're on pace to exceed your usual monthly dining budget. Consider cutting back.",
    actionLabel: "View details",
    priority: "medium",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    read: false,
  },
  {
    id: "insight_2",
    category: "reward",
    title: "Cashback Available",
    message: "You've earned ₦2,500 in cashback this month. Redeem now or let it accumulate.",
    actionLabel: "Redeem",
    priority: "low",
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    read: false,
  },
  {
    id: "insight_3",
    category: "educational",
    title: "Savings Tip",
    message: "Automating your savings to 10% of each paycheck could help you reach your goals faster.",
    actionLabel: "Set up auto-save",
    priority: "low",
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    read: true,
  },
]

export const defaultAdminControls: AdminControls = {
  enabledCategories: {
    empathetic: true,
    preventive: true,
    reward: true,
    educational: true,
    ambient: true,
  },
  rules: [
    {
      id: "rule_1",
      category: "preventive",
      name: "Monthly Budget Alert",
      trigger: "spending > 80% of monthly budget",
      message: "You're approaching your monthly budget limit.",
      enabled: true,
    },
    {
      id: "rule_2",
      category: "reward",
      name: "Cashback Milestone",
      trigger: "cashback_earned > 2000",
      message: "Congratulations! You've earned significant cashback.",
      enabled: true,
    },
    {
      id: "rule_3",
      category: "educational",
      name: "Savings Automation Tip",
      trigger: "first_deposit_received",
      message: "Learn how to automate your savings for financial goals.",
      enabled: true,
    },
    {
      id: "rule_4",
      category: "ambient",
      name: "Recurring Subscription Check",
      trigger: "recurring_transaction_detected",
      message: "Manage your recurring subscriptions.",
      enabled: true,
    },
  ],
}

export const quantoResponses = {
  salary_delay: {
    id: "salary_delay",
    category: "empathetic",
    message: "We noticed your salary came in later than usual.",
    explanation: "Salary pattern detection",
    actionLabel: "View support",
  },
  overspending_alert: {
    id: "overspending_alert",
    category: "preventive",
    message: "You're 15% above your usual spending.",
    explanation: "Spending threshold exceeded",
    actionLabel: "View tips",
  },
  savings_milestone: {
    id: "savings_milestone",
    category: "reward",
    message: "You've hit your savings goal for 3 months straight!",
    explanation: "Consistent savings detected",
    actionLabel: "Redeem",
  },
  first_salary: {
    id: "first_salary",
    category: "educational",
    message: "Starting a new job? Here are optimization tips.",
    explanation: "New salary income detected",
    actionLabel: "Learn more",
  },
  coffee_reminder: {
    id: "coffee_reminder",
    category: "ambient",
    message: "Recurring spending detected.",
    explanation: "Pattern-based spending alert",
    actionLabel: "Set limit",
  },
}
