import type { User, Transaction, QuantoInsight, AdminControls } from "./types"

export const mockUser: User = {
  id: "user_1",
  name: "Ada Okonkwo",
  email: "ada.okonkwo@email.com",
  phone: "+234 (0) 801 234 5678",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ada",
  accounts: [
    {
      id: "acc_1",
      name: "Checking Account",
      type: "checking",
      balance: 285430,
      accountNumber: "1234567890",
      routingNumber: "021000021",
    },
    {
      id: "acc_2",
      name: "Savings Account",
      type: "savings",
      balance: 450000,
      accountNumber: "0987654321",
      routingNumber: "021000021",
    },
  ],
  cards: [
    {
      id: "card_1",
      lastFour: "4242",
      type: "debit",
      cardholderName: "ADA OKONKWO",
      expiry: "12/26",
      isDefault: true,
      color: "from-blue-600 to-blue-800",
    },
    {
      id: "card_2",
      lastFour: "5555",
      type: "credit",
      cardholderName: "ADA OKONKWO",
      expiry: "08/25",
      isDefault: false,
      color: "from-purple-600 to-purple-800",
    },
  ],
}

export const recentTransactions: Transaction[] = [
  {
    id: "tx_1",
    date: "2025-11-12",
    vendor: "Starbucks Coffee",
    amount: 4500,
    category: "dining",
    type: "debit",
    icon: "☕",
  },
  {
    id: "tx_2",
    date: "2025-11-11",
    vendor: "Salary Deposit",
    amount: 285000,
    category: "income",
    type: "credit",
    icon: "💰",
  },
  {
    id: "tx_3",
    date: "2025-11-10",
    vendor: "Amazon Purchase",
    amount: 23500,
    category: "shopping",
    type: "debit",
    icon: "📦",
  },
  {
    id: "tx_4",
    date: "2025-11-09",
    vendor: "Electricity Bill",
    amount: 8200,
    category: "utilities",
    type: "debit",
    icon: "⚡",
  },
  {
    id: "tx_5",
    date: "2025-11-08",
    vendor: "Uber Trip",
    amount: 6800,
    category: "transport",
    type: "debit",
    icon: "🚗",
  },
  {
    id: "tx_6",
    date: "2025-11-07",
    vendor: "Netflix Subscription",
    amount: 2490,
    category: "entertainment",
    type: "debit",
    icon: "🎬",
  },
  {
    id: "tx_7",
    date: "2025-11-06",
    vendor: "Restaurant - The Bowl",
    amount: 18500,
    category: "dining",
    type: "debit",
    icon: "🍽️",
  },
  {
    id: "tx_8",
    date: "2025-11-05",
    vendor: "Gym Membership",
    amount: 15000,
    category: "health",
    type: "debit",
    icon: "💪",
  },
]

export const quantoInsights: QuantoInsight[] = [
  {
    id: "insight_1",
    category: "preventive",
    title: "Spending Alert",
    message: "You're on pace to exceed your usual monthly dining budget. Consider cutting back.",
    actionLabel: "View details",
    priority: "medium",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    read: false,
  },
  {
    id: "insight_2",
    category: "reward",
    title: "Cashback Available",
    message: "You've earned ₦2,500 in cashback this month. Redeem now or let it accumulate.",
    actionLabel: "Redeem",
    priority: "low",
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    read: false,
  },
  {
    id: "insight_3",
    category: "educational",
    title: "Savings Tip",
    message: "Automating your savings to 10% of each paycheck could help you reach your goals faster.",
    actionLabel: "Set up auto-save",
    priority: "low",
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    read: true,
  },
]

export const defaultAdminControls: AdminControls = {
  enabledCategories: {
    empathetic: true,
    preventive: true,
    reward: true,
    educational: true,
    ambient: true,
  },
  rules: [
    {
      id: "rule_1",
      category: "preventive",
      name: "Monthly Budget Alert",
      trigger: "spending > 80% of monthly budget",
      message: "You're approaching your monthly budget limit.",
      enabled: true,
    },
    {
      id: "rule_2",
      category: "reward",
      name: "Cashback Milestone",
      trigger: "cashback_earned > 2000",
      message: "Congratulations! You've earned significant cashback.",
      enabled: true,
    },
    {
      id: "rule_3",
      category: "educational",
      name: "Savings Automation Tip",
      trigger: "first_deposit_received",
      message: "Learn how to automate your savings for financial goals.",
      enabled: true,
    },
    {
      id: "rule_4",
      category: "ambient",
      name: "Recurring Subscription Check",
      trigger: "recurring_transaction_detected",
      message: "Manage your recurring subscriptions.",
      enabled: true,
    },
  ],
}

export const personas: any[] = [
  {
    id: "ada",
    name: "Ada",
    personaType: "Salaried Worker",
    balance: 120000,
    currentSpend: 47000,
    usualMonthlySpend: 50000,
    savingsStreak: 0,
  },
  {
    id: "malik",
    name: "Malik",
    personaType: "Student",
    balance: 32000,
    currentSpend: 57000,
    usualMonthlySpend: 50000,
    savingsStreak: 0,
  },
  {
    id: "ngozi",
    name: "Ngozi",
    personaType: "New Mother",
    balance: 95000,
    currentSpend: 40000,
    usualMonthlySpend: 45000,
    savingsStreak: 1,
  },
  {
    id: "tolu",
    name: "Tolu",
    personaType: "Freelancer",
    balance: 280000,
    currentSpend: 41000,
    usualMonthlySpend: 65000,
    savingsStreak: 0,
  },
  {
    id: "raymond",
    name: "Raymond",
    personaType: "Small Business Owner",
    balance: 520000,
    currentSpend: 95000,
    usualMonthlySpend: 120000,
    savingsStreak: 3,
  },
]

export const quantoResponses: Record<string, any> = {
  salary_delay: {
    id: "salary_delay",
    category: "empathetic",
    message: "We noticed your salary came in later than usual.",
    explanation: "Salary pattern detection",
    actionLabel: "View support",
  },
  overspending_alert: {
    id: "overspending_alert",
    category: "preventive",
    message: "You're 15% above your usual spending.",
    explanation: "Spending threshold exceeded",
    actionLabel: "View tips",
  },
  savings_milestone: {
    id: "savings_milestone",
    category: "reward",
    message: "You've hit your savings goal for 3 months straight!",
    explanation: "Consistent savings detected",
    actionLabel: "Redeem",
  },
  first_salary: {
    id: "first_salary",
    category: "educational",
    message: "Starting a new job? Here are optimization tips.",
    explanation: "New salary income detected",
    actionLabel: "Learn more",
  },
  coffee_reminder: {
    id: "coffee_reminder",
    category: "ambient",
    message: "Recurring spending detected.",
    explanation: "Pattern-based spending alert",
    actionLabel: "Set limit",
  },
}
